- name: Configure VM and install Docker
  hosts: all
  become: true

  tasks:
    - name: Wait for cloud-init to finish (if running)
      shell: cloud-init status --wait
      register: cloud_init_status
      changed_when: false
      failed_when: false
      ignore_errors: true

    - name: Wait until APT lock is released
      shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

    - name: Install required packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Ensure SSH allows password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: 'PasswordAuthentication yes'
      notify: Restart SSH

    - name: Ensure SSH allows PAM (needed for passwords)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^UsePAM'
        line: 'UsePAM yes'
      notify: Restart SSH

    - name: Ensure SSH allows user login (no forced key-only login)
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: 'ChallengeResponseAuthentication yes'
      notify: Restart SSH

    - name: Flush handlers (restart SSH now if needed)
      meta: flush_handlers

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Set up Docker repository
      copy:
        content: |
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable
        dest: /etc/apt/sources.list.d/docker.list

    - name: Update APT cache after adding Docker repo
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Wait until APT lock is released before Docker install
      shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

    - name: Install Docker and dependencies (with retries and lock timeout)
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes
        force_apt_get: yes
      register: result
      retries: 10
      delay: 10
      until: result is succeeded

  handlers:
    - name: Restart SSH
      service:
        name: ssh
        state: restarted
