name: Backend Deployment

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  security:
    name: Security Checks for backend
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Check for Secrets
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: ".github/gitleaks.toml"

  build:
    name: Build Docker Image for backend
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Build Image
        run: docker build -t vm-deployment-backend:latest ./backend

  stop:
    name: Stop Running backend
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop Old Container (if exists)
        run: |
          docker ps -a | grep vm-deployment-backend && docker stop vm-deployment-backend || true
          docker ps -a | grep vm-deployment-backend && docker rm vm-deployment-backend || true

  start:
    name: Start New backend
    runs-on: self-hosted
    needs: stop
    steps:
      - name: Check .env exists
        run: |
          if [ ! -f /opt/vm-deployment/.env ]; then
            echo ".env file is missing! Abort."
            exit 1
          fi
      - name: Run New Container
        run: |
          docker run -d --network host \
            --env-file /opt/vm-deployment/.env \
            -v ~/VM-management:/app/../VM-management \
            -v ~/.ssh:/root/.ssh \
            --name vm-deployment-backend \
            vm-deployment-backend:latest
