name: Deployment

on:
  push:
    branches:
      - main

jobs:
  checkout:
    name: Checkout Code
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

  build:
    name: Build Docker Image
    runs-on: self-hosted
    needs: checkout
    steps:
      - name: Build Image
        run: docker build -t vm-deployment-app:latest .

  stop:
    name: Stop Running Container
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop Old Container (if exists)
        run: |
          docker ps -a | grep vm-deployment-app && docker stop vm-deployment-app || true
          docker ps -a | grep vm-deployment-app && docker rm vm-deployment-app || true

  start:
    name: Start New Container
    runs-on: self-hosted
    needs: stop
    steps:
      - name: Check .env exists
        run: |
          if [ ! -f /opt/vm-deployment/.env ]; then
            echo ".env file is missing! Abort."
            exit 1
          fi
      - name: Run New Container
        run: |
          docker run -d --network host \
            --env-file /opt/vm-deployment/.env \
            -v ~/VM-management:/app/../VM-management \
            -v ~/.ssh:/root/.ssh \
            --name vm-deployment-app \
            vm-deployment-app:latest
